shared:
  aws_region: "eu-west-3"
  project_name: "secure-platform"

  availability_zones:
    - "eu-west-3a"
    - "eu-west-3b"

  allowed_ingress_cidr_blocks:
    - "0.0.0.0/0"

  alb_internal: false
  alb_idle_timeout: 60
  alb_enable_deletion_protection: false

  enable_waf: true
  waf_default_action: "allow"

  db_username: "postgres"

environments:
  dev:
    environment: "dev"

    vpc_cidr: "{{ 'DEV_VPC_CIDR' | env }}"

    public_subnet_cidrs:
      - "{{ 'DEV_PUBLIC_SUBNET_CIDR_1' | env }}"
      - "{{ 'DEV_PUBLIC_SUBNET_CIDR_2' | env }}"

    private_app_subnet_cidrs:
      - "{{ 'DEV_PRIVATE_APP_SUBNET_CIDR_1' | env }}"
      - "{{ 'DEV_PRIVATE_APP_SUBNET_CIDR_2' | env }}"

    private_db_subnet_cidrs:
      - "{{ 'DEV_PRIVATE_DB_SUBNET_CIDR_1' | env }}"
      - "{{ 'DEV_PRIVATE_DB_SUBNET_CIDR_2' | env }}"

    waf_managed_rule_groups:
      - name: "AWSManagedRulesCommonRuleSet"
        priority: 10
        vendor_name: "AWS"
        override_action: "count"

      - name: "AWSManagedRulesKnownBadInputsRuleSet"
        priority: 20
        vendor_name: "AWS"
        override_action: "count"

  staging:
    environment: "staging"

    vpc_cidr: "{{ 'STAGING_VPC_CIDR' | env }}"

    public_subnet_cidrs:
      - "{{ 'STAGING_PUBLIC_SUBNET_CIDR_1' | env }}"
      - "{{ 'STAGING_PUBLIC_SUBNET_CIDR_2' | env }}"

    private_app_subnet_cidrs:
      - "{{ 'STAGING_PRIVATE_APP_SUBNET_CIDR_1' | env }}"
      - "{{ 'STAGING_PRIVATE_APP_SUBNET_CIDR_2' | env }}"

    private_db_subnet_cidrs:
      - "{{ 'STAGING_PRIVATE_DB_SUBNET_CIDR_1' | env }}"
      - "{{ 'STAGING_PRIVATE_DB_SUBNET_CIDR_2' | env }}"

    waf_managed_rule_groups:
      - name: "AWSManagedRulesCommonRuleSet"
        priority: 10
        vendor_name: "AWS"
        override_action: "none"

      - name: "AWSManagedRulesKnownBadInputsRuleSet"
        priority: 20
        vendor_name: "AWS"
        override_action: "none"

  prod:
    environment: "prod"

    vpc_cidr: "{{ 'PROD_VPC_CIDR' | env }}"

    public_subnet_cidrs:
      - "{{ 'PROD_PUBLIC_SUBNET_CIDR_1' | env }}"
      - "{{ 'PROD_PUBLIC_SUBNET_CIDR_2' | env }}"

    private_app_subnet_cidrs:
      - "{{ 'PROD_PRIVATE_APP_SUBNET_CIDR_1' | env }}"
      - "{{ 'PROD_PRIVATE_APP_SUBNET_CIDR_2' | env }}"

    private_db_subnet_cidrs:
      - "{{ 'PROD_PRIVATE_DB_SUBNET_CIDR_1' | env }}"
      - "{{ 'PROD_PRIVATE_DB_SUBNET_CIDR_2' | env }}"

    waf_managed_rule_groups:
      - name: "AWSManagedRulesCommonRuleSet"
        priority: 10
        vendor_name: "AWS"
        override_action: "none"

      - name: "AWSManagedRulesKnownBadInputsRuleSet"
        priority: 20
        vendor_name: "AWS"
        override_action: "none"
